name: Convert LaTeX to HTML for Blog

on:
  push:
    paths:
      - "**.tex"   # trigger when any .tex file changes anywhere in repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Pandoc and TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

      - name: Convert all .tex files → .html
        run: |
          find . -name "*.tex" | while read file; do
            base=$(basename "$file" .tex)
            pandoc "$file" -s -o "${base}.html"
          done

      - name: Add links for new posts into index.html
        run: |
          for file in *.tex; do
            base=$(basename "$file" .tex)
            if ! grep -q "$base.html" index.html; then
              sed -i "/<\/body>/i <p><a href=\"$base.html\">$base</a></p>" index.html
            fi
          done

      - name: Commit generated HTML
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add *.html index.html
          git commit -m "Auto-converted TeX to HTML" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
